[package]
name = "t"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-tar = "0.3.0"
tokio = { version = "1.22.0", features = ["macros", "rt-multi-thread", "io-util"], default-features = false }
async-compression = { version = "0.3.15", features = ["gzip", "tokio"] }
